const BASE_URL = "http://0.0.0.0:3000/";

export const fetchScenarios = async () => {
  /*
  const response = await fetch(`${BASE_URL}loadScenarios`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });

  console.info(await response.json());

  return await response.json();
  */

  return {
    scenarios: [
      {
        _id: "647b6f34e8ea7cd1e15920e7",
        name: "scenario-1",
        itens: [
          {
            canvasId: "platformThreeCanvas",
            imageId: "platform3",
            frameX: 0,
            frameY: 0,
            width: 150,
            height: 96,
            x: 558,
            y: 599,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformTwo2Canvas",
            imageId: "platform2",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 43,
            x: 1432,
            y: 291,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne1Canvas",
            imageId: "platform1",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            x: 882,
            y: 427,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne2Canvas",
            imageId: "platform1",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            x: 982,
            y: 427,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne3Canvas",
            imageId: "platform1",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            x: 1082,
            y: 427,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformTwo2Canvas",
            imageId: "platform2",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 43,
            x: 1332,
            y: 291,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformTwo1Canvas",
            imageId: "platform2",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 43,
            x: 1132,
            y: 291,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformTwo2Canvas",
            imageId: "platform2",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 43,
            x: 1232,
            y: 291,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformThreeCanvas",
            imageId: "platform3",
            frameX: 0,
            frameY: 0,
            width: 150,
            height: 96,
            x: 721,
            y: 499,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass1Canvas",
            x: 1654,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 1954,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "signRightCanvas",
            imageId: "sign",
            frameX: 0,
            frameY: 0,
            width: 52,
            height: 64,
            x: 1677,
            y: 522,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCave6Canvas",
            x: 2057,
            y: 285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2553,
            y: 585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2257,
            y: 485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2257,
            y: 385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround4Canvas",
            x: 2157,
            y: 385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround1Canvas",
            x: 2157,
            y: 285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround2Canvas",
            x: 2257,
            y: 285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2357,
            y: 388,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2357,
            y: 488,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround6Canvas",
            x: 2457,
            y: 489,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround2Canvas",
            x: 2357,
            y: 288,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2354,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave9Canvas",
            x: 2454,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave8Canvas",
            x: 2054,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave8Canvas",
            x: 2154,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave8Canvas",
            x: 2254,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround4Canvas",
            x: 2157,
            y: 485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave1Canvas",
            x: 2157,
            y: 285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave2Canvas",
            x: 2257,
            y: 285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave2Canvas",
            x: 2357,
            y: 285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2457,
            y: 387,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass1Canvas",
            x: 2454,
            y: 485,
            colitionGround: true,
            colitionWall: true,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2357,
            y: 185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2357,
            y: 85,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2257,
            y: 85,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2257,
            y: 185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2157,
            y: 185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass4Canvas",
            x: 2057,
            y: 185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass1Canvas",
            x: 2057,
            y: 85,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2157,
            y: 85,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass4Canvas",
            x: 1653,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 1953,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2053,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2153,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2253,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2353,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2453,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2553,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "tree3Canvas",
            imageId: "tree3",
            frameX: 0,
            frameY: 0,
            width: 280,
            height: 305,
            x: 2298,
            y: -220,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "tree1Canvas",
            imageId: "tree1",
            frameX: 0,
            frameY: 0,
            width: 400,
            height: 470,
            x: 2043,
            y: -384,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass7Canvas",
            x: 1653,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "tree4Canvas",
            imageId: "tree4",
            frameX: 0,
            frameY: 0,
            width: 435,
            height: 480,
            x: 1029,
            y: -189,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass7Canvas",
            x: 2057,
            y: 385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2157,
            y: 385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "tree4Canvas",
            imageId: "tree4",
            frameX: 0,
            frameY: 0,
            width: 435,
            height: 480,
            x: 1646,
            y: 107,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformTwo3Canvas",
            imageId: "platform2",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 43,
            x: 1532,
            y: 291,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 1854,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 1754,
            y: 585,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 1753,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 1853,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass8Canvas",
            x: 1753,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2457,
            y: 287,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2557,
            y: 387,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2657,
            y: 387,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2557,
            y: 287,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2657,
            y: 287,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2757,
            y: 287,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2757,
            y: 387,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2857,
            y: 187,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2846,
            y: 487,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2957,
            y: 187,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2857,
            y: 387,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2558,
            y: 187,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2658,
            y: 187,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2757,
            y: 187,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2957,
            y: 287,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2957,
            y: 387,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2557,
            y: 285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2457,
            y: 85,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2456,
            y: 185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2557,
            y: 85,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave1Canvas",
            x: 2556,
            y: 185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2656,
            y: 85,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass8Canvas",
            x: 2457,
            y: 285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass8Canvas",
            x: 2656,
            y: 185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2554,
            y: 485,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround6Canvas",
            x: 3057,
            y: 387,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround6Canvas",
            x: 3057,
            y: 287,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround6Canvas",
            x: 3057,
            y: 187,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround3Canvas",
            x: 3052,
            y: 87,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround2Canvas",
            x: 2952,
            y: 87,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround2Canvas",
            x: 2852,
            y: 87,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround2Canvas",
            x: 2756,
            y: 90,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass3Canvas",
            x: 2756,
            y: 85,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2756,
            y: 185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "signDeathCanvas",
            imageId: "sign",
            frameX: 0,
            frameY: 1,
            width: 52,
            height: 64,
            x: 3227,
            y: 421,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2746,
            y: 487,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround4Canvas",
            x: 2657,
            y: 487,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2746,
            y: 587,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround4Canvas",
            x: 2657,
            y: 587,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass3Canvas",
            x: 2654,
            y: 485,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass6Canvas",
            x: 2653,
            y: 585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2946,
            y: 588,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2946,
            y: 488,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne1Canvas",
            imageId: "platform1",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            x: 2879,
            y: 485,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround4Canvas",
            x: 2657,
            y: 687,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass6Canvas",
            x: 2653,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2746,
            y: 687,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2946,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2650,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2650,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2747,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2847,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2980,
            y: 485,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass6Canvas",
            x: 3080,
            y: 585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass6Canvas",
            x: 3080,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass4Canvas",
            x: 2980,
            y: 585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass4Canvas",
            x: 2980,
            y: 685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2550,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2450,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2251,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2350,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2450,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2550,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2649,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2749,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2849,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2251,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2350,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2450,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2550,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2650,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2750,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2849,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround6Canvas",
            x: 2947,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2850,
            y: 1085,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2750,
            y: 1085,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround6Canvas",
            x: 2949,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround6Canvas",
            x: 2949,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround3Canvas",
            x: 2987,
            y: 949,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne3Canvas",
            imageId: "platform1",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            x: 3180,
            y: 485,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 3080,
            y: 485,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass7Canvas",
            x: 2980,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 3080,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave2Canvas",
            x: 2550,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2450,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave1Canvas",
            x: 2452,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave2Canvas",
            x: 2350,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave9Canvas",
            x: 2650,
            y: 1185,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2750,
            y: 1185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass6Canvas",
            x: 2850,
            y: 1185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2352,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround9Canvas",
            x: 2989,
            y: 1045,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne3Canvas",
            imageId: "platform1",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            x: 3050,
            y: 1085,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2551,
            y: 1085,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2651,
            y: 1085,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass1Canvas",
            x: 2651,
            y: 1085,
            colitionGround: true,
            colitionWall: true,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2451,
            y: 1085,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2351,
            y: 1085,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2251,
            y: 1085,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2350,
            y: 1185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2450,
            y: 1185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass1Canvas",
            x: 2450,
            y: 1185,
            colitionGround: true,
            colitionWall: true,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2252,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave9Canvas",
            x: 2450,
            y: 1285,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 2550,
            y: 1185,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass1Canvas",
            x: 2350,
            y: 1285,
            colitionGround: true,
            colitionWall: true,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave3Canvas",
            x: 1853,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass7Canvas",
            x: 1852,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave3Canvas",
            x: 1952,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass7Canvas",
            x: 1952,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2051,
            y: 981,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2151,
            y: 986,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2051,
            y: 985,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2151,
            y: 886,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2051,
            y: 883,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave1Canvas",
            x: 2051,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave2Canvas",
            x: 2150,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave2Canvas",
            x: 2250,
            y: 885,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2152,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2053,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 1953,
            y: 785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround7Canvas",
            x: 1993,
            y: 1081,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2151,
            y: 1085,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround8Canvas",
            x: 2151,
            y: 1185,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround7Canvas",
            x: 2192,
            y: 1218,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround8Canvas",
            x: 2292,
            y: 1218,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2251,
            y: 1119,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround4Canvas",
            x: 2051,
            y: 1081,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround7Canvas",
            x: 2051,
            y: 1181,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround9Canvas",
            x: 2093,
            y: 1081,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2249,
            y: 1585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2449,
            y: 1385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave9Canvas",
            x: 2349,
            y: 1385,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave8Canvas",
            x: 2249,
            y: 1385,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave8Canvas",
            x: 2149,
            y: 1385,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave8Canvas",
            x: 2049,
            y: 1385,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundCave8Canvas",
            x: 1949,
            y: 1385,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass1Canvas",
            x: 1849,
            y: 1385,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass4Canvas",
            x: 1849,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass7Canvas",
            x: 1849,
            y: 1585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass8Canvas",
            x: 1949,
            y: 1585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass8Canvas",
            x: 2149,
            y: 1785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave3Canvas",
            x: 2049,
            y: 1585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 1949,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass4Canvas",
            x: 2049,
            y: 1685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass7Canvas",
            x: 2049,
            y: 1785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2049,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2149,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2249,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2349,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2149,
            y: 1585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2149,
            y: 1685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2349,
            y: 1585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2550,
            y: 1285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2650,
            y: 1285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2549,
            y: 1385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2750,
            y: 1285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass6Canvas",
            x: 2850,
            y: 1285,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2849,
            y: 1385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2649,
            y: 1385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave1Canvas",
            x: 2749,
            y: 1385,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2749,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave1Canvas",
            x: 2649,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2649,
            y: 1585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave1Canvas",
            x: 2549,
            y: 1584,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2549,
            y: 1684,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave1Canvas",
            x: 2449,
            y: 1684,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2449,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2449,
            y: 1585,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2549,
            y: 1485,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass8Canvas",
            x: 2249,
            y: 1785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 2449,
            y: 1784,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass8Canvas",
            x: 2349,
            y: 1785,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2249,
            y: 1685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundGrass5Canvas",
            x: 2349,
            y: 1685,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2846,
            y: 587,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2846,
            y: 687,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCaveGround",
            frameX: 1,
            frameY: 1,
            width: 100,
            height: 100,
            canvasId: "groundCaveGround5Canvas",
            x: 2857,
            y: 287,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne3Canvas",
            imageId: "platform1",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            x: 1545,
            y: 1473,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne2Canvas",
            imageId: "platform1",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            x: 1445,
            y: 1473,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne1Canvas",
            imageId: "platform1",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            x: 1345,
            y: 1473,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformThreeCanvas",
            imageId: "platform3",
            frameX: 0,
            frameY: 0,
            width: 150,
            height: 96,
            x: 1071,
            y: 1519,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass1Canvas",
            x: 432,
            y: 1591,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 532,
            y: 1591,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 0,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass7Canvas",
            x: 432,
            y: 1691,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass8Canvas",
            x: 532,
            y: 1691,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 2,
            width: 100,
            height: 100,
            canvasId: "groundGrass9Canvas",
            x: 829,
            y: 1696,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "tree2Canvas",
            imageId: "tree2",
            frameX: 0,
            frameY: 0,
            width: 550,
            height: 610,
            x: 270,
            y: 1025,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 629,
            y: 1596,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass2Canvas",
            x: 729,
            y: 1596,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave2Canvas",
            x: 629,
            y: 1692,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundGrass",
            frameX: 2,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundGrass3Canvas",
            x: 829,
            y: 1596,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            imageId: "groundCave",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            canvasId: "groundCave2Canvas",
            x: 729,
            y: 1694,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "signLeftCanvas",
            imageId: "sign",
            frameX: 1,
            frameY: 0,
            width: 52,
            height: 64,
            x: 1863,
            y: 1321,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "signDownCanvas",
            imageId: "sign",
            frameX: 1,
            frameY: 1,
            width: 52,
            height: 64,
            x: 2712,
            y: 420,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "platformOne2Canvas",
            imageId: "platform1",
            frameX: 1,
            frameY: 0,
            width: 100,
            height: 100,
            x: 2950,
            y: 1085,
            colitionGround: true,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "signDeathCanvas",
            imageId: "sign",
            frameX: 0,
            frameY: 1,
            width: 52,
            height: 64,
            x: 3078,
            y: 1021,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "tree3Canvas",
            imageId: "tree3",
            frameX: 0,
            frameY: 0,
            width: 280,
            height: 305,
            x: 2939,
            y: 180,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "signRightCanvas",
            imageId: "sign",
            frameX: 0,
            frameY: 0,
            width: 52,
            height: 64,
            x: 1553,
            y: 227,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
          {
            canvasId: "signLeftCanvas",
            imageId: "sign",
            frameX: 1,
            frameY: 0,
            width: 52,
            height: 64,
            x: 2650,
            y: 1020,
            colitionGround: false,
            colitionWall: false,
            type: "ground",
          },
        ],
        __v: 0,
      },
    ],
  };
};
